# Generated by Django 2.1.15 on 2020-04-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=30)),
                ('rank', models.DecimalField(decimal_places=1, max_digits=5)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.CharField(max_length=10)),
                ('password', models.TextField()),
                ('hitcount', models.IntegerField()),
            ],
        ),
    ]
